# Docker profile configuration
spring.application.name=futpitacos

# Server
server.port=8090
server.shutdown=graceful

# Logging
logging.level.root=INFO
logging.level.com.guibsonsoftwares.futpitacos=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Timezone
spring.jackson.time-zone=America/Sao_Paulo

